# Generated by Django 4.1.3 on 2022-11-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('country', models.CharField(choices=[('ghana', 'GHANA'), ('uae', 'UAE'), ('ivory cost', 'IVORY COST'), ('senegal', 'SENEGAL'), ('turkey', 'TURKEY')], default='ghana', max_length=15)),
                ('category_no', models.CharField(max_length=5)),
            ],
        ),
    ]
