# Generated by Django 4.1.3 on 2022-11-24 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_remove_category_category_no_alter_category_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='subCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCategory', models.CharField(max_length=30, unique=True)),
                ('categoryL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.category', to_field='category')),
            ],
        ),
    ]
