# Generated by Django 4.1.3 on 2022-12-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
