# Generated by Django 4.1.3 on 2023-01-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.ImageField(blank=True, default=None, max_length=250, null=True, upload_to='product/'),
        ),
    ]
