# Generated by Django 4.1.3 on 2023-01-11 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_alter_product_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Brand',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Product.brand', to_field='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Product.category', to_field='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='costInUsd',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='perPointCost',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.018, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='points',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchaseAmount',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchaseCurrency',
            field=models.CharField(blank=True, choices=[('ghs', 'GHS'), ('usd', 'USD')], default='ghs', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='subCategory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Product.subcategory', to_field='subCategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='usdConversionRate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
