# Generated by Django 4.1.3 on 2023-01-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='perPointCost',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.957, max_digits=5),
        ),
    ]
